export const category = [
  { value: "javascript", name: "Javascript" },
  { value: "Java", name: "Java" },
  { value: "Python", name: "Python" },
  { value: "C/C++", name: "C/C++" },
  { value: "PHP", name: "PHP" },
  { value: "R", name: "R" },
  { value: "C#", name: "C#" },
  { value: "Swift", name: "Swift" },
  { value: "HTML CSS", name: "HTML CSS" },
  { value: "JSP", name: "JSP" },
  { value: "TypeScript", name: "TypeScript" },
  { value: "Rudy", name: "Rudy" },
  { value: "Objective-C", name: "Objective-C" },
  { value: "Go", name: "Go" },
  { value: "VisiualBasic VBA", name: "VisiualBasic VBA" },
  { value: "mfc", name: "mfc" },
  { value: "Kotlin", name: "Kotlin" },
];
