export const category = [
  { name: "Javascript" },
  { name: "Java" },
  { name: "Python" },
  { name: "C,C++" },
  { name: "PHP" },
  { name: "R" },
  { name: "C#" },
  { name: "Swift" },
  { name: "HTML CSS" },
  { name: "JSP" },
  { name: "TypeScript" },
  { name: "Rudy" },
  { name: "Objective-C" },
  { name: "Go" },
  { name: "VisiualBasic VBA" },
  { name: "mfc" },
  { name: "Kotlin" },
];
