export const category = [
  { value: "1Javascript", name: "Javascript" },
  { value: "2Java", name: "Java" },
  { value: "3Python", name: "Python" },
  { value: "4C/C++", name: "C/C++" },
  { value: "5PHP", name: "PHP" },
  { value: "6R", name: "R" },
  { value: "7C#", name: "C#" },
  { value: "8Swift", name: "Swift" },
  { value: "9HTML CSS", name: "HTML CSS" },
  { value: "10JSP", name: "JSP" },
  { value: "11TypeScript", name: "TypeScript" },
  { value: "12Rudy", name: "Rudy" },
  { value: "13Objective-C", name: "Objective-C" },
  { value: "14Go", name: "Go" },
  { value: "15VisiualBasic VBA", name: "VisiualBasic VBA" },
  { value: "16mfc", name: "mfc" },
  { value: "17Kotlin", name: "Kotlin" },
];
